builds:
- id: onionpipe
  binary: onionpipe
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64

brews:
- tap:
    owner: cmars
    name: homebrew-onionpipe
    branch: main
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
  dependencies:
  - tor
