version: '3'

volumes:
  nextcloud:
  db:
  onionpipe:

services:
  onionpipe:
    image: ghcr.io/cmars/onionpipe:main
    restart: always
    command: --secrets /var/lib/onionpipe/secrets.json app:80~80@nextcloud
    volumes:
      - onionpipe:/var/lib/onionpipe

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
